@startuml
actor Пользователь
participant Клавиатура
participant Микроконтроллер
participant "Дисплей " as Дисплей


loop Ввод выражения
    Пользователь -> Клавиатура: Нажатие кнопки
    Клавиатура --> Микроконтроллер: Код кнопки

    alt Нажата цифра (0–9)
        Микроконтроллер -> Микроконтроллер: Добавление цифры к операнду
        Микроконтроллер -> Дисплей: Показ введённого числа

    else Нажата операция (+, -, *, /)
        Микроконтроллер -> Микроконтроллер: Сохранение выбранной операции

    else Нажата кнопка '='
        Микроконтроллер -> Микроконтроллер: Проверка введённых данных

        alt Выражение введено не полностьюх

        else Деление на ноль
            Микроконтроллер -> Дисплей: Показ Err
        else Корректное выражение
            Микроконтроллер -> Микроконтроллер: Вычисление результата

            alt Результат помещается на дисплее
                Микроконтроллер -> Дисплей: Показ результата
            else Результат не помещается
                Микроконтроллер -> Дисплей: Показ Err
                 end

            end
    end
end
@enduml